apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-service
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
