apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-service
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.amqp }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: {{ .Values.service.ports.management }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
