apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cockroachdb.fullname" . }}
  labels:
    {{- include "cockroachdb.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cockroachdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cockroachdb.selectorLabels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /cockroach/cockroach
            {{- if .Values.cockroachdb.singleNode }}
            - start-single-node
            {{- else }}
            - start
            {{- end }}
            - --insecure={{ .Values.cockroachdb.insecure }}
            - --listen-addr={{ .Values.cockroachdb.listenAddr }}
            - --advertise-addr={{ .Values.cockroachdb.advertiseAddr }}
            - --http-addr={{ .Values.cockroachdb.httpAddr }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.ports.grpc }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.ports.http }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cockroachdb-data
              mountPath: /cockroach/cockroach-data
      volumes:
        - name: cockroachdb-data
          {{- if eq .Values.storage.type "emptyDir" }}
          emptyDir: {}
          {{- else if eq .Values.storage.type "persistentVolumeClaim" }}
          persistentVolumeClaim:
            claimName: {{ include "cockroachdb.fullname" . }}-pvc
          {{- end }}
