apiVersion: v1
kind: Service
metadata:
  name: {{ include "cockroachdb.fullname" . }}-public
  labels:
    {{- include "cockroachdb.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cockroachdb.selectorLabels" . | nindent 4 }}
