server:
  port: 8083

spring:
  application:
    name: benefit-estimation-service

  datasource:
    url: jdbc:h2:mem:benefitdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

# External service configurations
order-service:
  url: http://localhost:8082/api/orders

product-service:
  url: http://localhost:8081/api/products

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  packages-to-scan: com.example.benefitestimationservice.controller

logging:
  level:
    com.example.benefitestimationservice: DEBUG
    org.springframework.web: DEBUG
