server:
  port: 8084

spring:
  application:
    name: payout-service
  
  datasource:
    url: jdbc:h2:mem:payoutdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

# External service configurations
benefit-estimation-service:
  url: http://localhost:8083/api/benefit-estimations

order-service:
  url: http://localhost:8082/api/orders

logging:
  level:
    com.example.payoutservice: DEBUG
    org.springframework.web: DEBUG
